platform :ios, '8.0'
pod 'RestKit/ObjectMapping', '~> 0.23.3'
pod 'AFNetworking', '~> 2.3.1'
pod 'ASDepthModal', '~> 1.0.0'
pod 'Reachability', '~> 3.1.1'
pod 'protobuf-ios'
pod 'AMap2DMap', '~> 2.4.2'
pod 'AMapSearch', '~> 2.4.1'