// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

#ifndef PROTOBUF_chat_2eproto__INCLUDED
#define PROTOBUF_chat_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace chat {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_chat_2eproto();
void protobuf_AssignDesc_chat_2eproto();
void protobuf_ShutdownFile_chat_2eproto();

class Question;
class Answer;

enum ChatRequestType {
  ChatTypeSendPTP = 8000,
  ChatTypeSendPTG = 8001,
  ChatTypeOnLine = 8002,
  ChatTypeOffLine = 8003
};
bool ChatRequestType_IsValid(int value);
const ChatRequestType ChatRequestType_MIN = ChatTypeSendPTP;
const ChatRequestType ChatRequestType_MAX = ChatTypeOffLine;
const int ChatRequestType_ARRAYSIZE = ChatRequestType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ChatRequestType_descriptor();
inline const ::std::string& ChatRequestType_Name(ChatRequestType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ChatRequestType_descriptor(), value);
}
inline bool ChatRequestType_Parse(
    const ::std::string& name, ChatRequestType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ChatRequestType>(
    ChatRequestType_descriptor(), name, value);
}
// ===================================================================

class Question : public ::google::protobuf::Message {
 public:
  Question();
  virtual ~Question();

  Question(const Question& from);

  inline Question& operator=(const Question& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Question& default_instance();

  void Swap(Question* other);

  // implements Message ----------------------------------------------

  Question* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Question& from);
  void MergeFrom(const Question& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 mid = 1;
  inline bool has_mid() const;
  inline void clear_mid();
  static const int kMidFieldNumber = 1;
  inline ::google::protobuf::int64 mid() const;
  inline void set_mid(::google::protobuf::int64 value);

  // required int64 tid = 2;
  inline bool has_tid() const;
  inline void clear_tid();
  static const int kTidFieldNumber = 2;
  inline ::google::protobuf::int64 tid() const;
  inline void set_tid(::google::protobuf::int64 value);

  // required .chat.ChatRequestType type = 3;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 3;
  inline ::chat::ChatRequestType type() const;
  inline void set_type(::chat::ChatRequestType value);

  // optional string message = 4;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 4;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // optional bytes pic = 5;
  inline bool has_pic() const;
  inline void clear_pic();
  static const int kPicFieldNumber = 5;
  inline const ::std::string& pic() const;
  inline void set_pic(const ::std::string& value);
  inline void set_pic(const char* value);
  inline void set_pic(const void* value, size_t size);
  inline ::std::string* mutable_pic();
  inline ::std::string* release_pic();
  inline void set_allocated_pic(::std::string* pic);

  // optional bytes video = 6;
  inline bool has_video() const;
  inline void clear_video();
  static const int kVideoFieldNumber = 6;
  inline const ::std::string& video() const;
  inline void set_video(const ::std::string& value);
  inline void set_video(const char* value);
  inline void set_video(const void* value, size_t size);
  inline ::std::string* mutable_video();
  inline ::std::string* release_video();
  inline void set_allocated_video(::std::string* video);

  // @@protoc_insertion_point(class_scope:chat.Question)
 private:
  inline void set_has_mid();
  inline void clear_has_mid();
  inline void set_has_tid();
  inline void clear_has_tid();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_message();
  inline void clear_has_message();
  inline void set_has_pic();
  inline void clear_has_pic();
  inline void set_has_video();
  inline void clear_has_video();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 mid_;
  ::google::protobuf::int64 tid_;
  ::std::string* message_;
  ::std::string* pic_;
  ::std::string* video_;
  int type_;
  friend void  protobuf_AddDesc_chat_2eproto();
  friend void protobuf_AssignDesc_chat_2eproto();
  friend void protobuf_ShutdownFile_chat_2eproto();

  void InitAsDefaultInstance();
  static Question* default_instance_;
};
// -------------------------------------------------------------------

class Answer : public ::google::protobuf::Message {
 public:
  Answer();
  virtual ~Answer();

  Answer(const Answer& from);

  inline Answer& operator=(const Answer& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Answer& default_instance();

  void Swap(Answer* other);

  // implements Message ----------------------------------------------

  Answer* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Answer& from);
  void MergeFrom(const Answer& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline const ::std::string& result() const;
  inline void set_result(const ::std::string& value);
  inline void set_result(const char* value);
  inline void set_result(const char* value, size_t size);
  inline ::std::string* mutable_result();
  inline ::std::string* release_result();
  inline void set_allocated_result(::std::string* result);

  // required .chat.ChatRequestType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::chat::ChatRequestType type() const;
  inline void set_type(::chat::ChatRequestType value);

  // optional string message = 3;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 3;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // optional bytes pic = 4;
  inline bool has_pic() const;
  inline void clear_pic();
  static const int kPicFieldNumber = 4;
  inline const ::std::string& pic() const;
  inline void set_pic(const ::std::string& value);
  inline void set_pic(const char* value);
  inline void set_pic(const void* value, size_t size);
  inline ::std::string* mutable_pic();
  inline ::std::string* release_pic();
  inline void set_allocated_pic(::std::string* pic);

  // optional bytes video = 5;
  inline bool has_video() const;
  inline void clear_video();
  static const int kVideoFieldNumber = 5;
  inline const ::std::string& video() const;
  inline void set_video(const ::std::string& value);
  inline void set_video(const char* value);
  inline void set_video(const void* value, size_t size);
  inline ::std::string* mutable_video();
  inline ::std::string* release_video();
  inline void set_allocated_video(::std::string* video);

  // @@protoc_insertion_point(class_scope:chat.Answer)
 private:
  inline void set_has_result();
  inline void clear_has_result();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_message();
  inline void clear_has_message();
  inline void set_has_pic();
  inline void clear_has_pic();
  inline void set_has_video();
  inline void clear_has_video();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* result_;
  ::std::string* message_;
  ::std::string* pic_;
  ::std::string* video_;
  int type_;
  friend void  protobuf_AddDesc_chat_2eproto();
  friend void protobuf_AssignDesc_chat_2eproto();
  friend void protobuf_ShutdownFile_chat_2eproto();

  void InitAsDefaultInstance();
  static Answer* default_instance_;
};
// ===================================================================


// ===================================================================

// Question

// required int64 mid = 1;
inline bool Question::has_mid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Question::set_has_mid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Question::clear_has_mid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Question::clear_mid() {
  mid_ = GOOGLE_LONGLONG(0);
  clear_has_mid();
}
inline ::google::protobuf::int64 Question::mid() const {
  // @@protoc_insertion_point(field_get:chat.Question.mid)
  return mid_;
}
inline void Question::set_mid(::google::protobuf::int64 value) {
  set_has_mid();
  mid_ = value;
  // @@protoc_insertion_point(field_set:chat.Question.mid)
}

// required int64 tid = 2;
inline bool Question::has_tid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Question::set_has_tid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Question::clear_has_tid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Question::clear_tid() {
  tid_ = GOOGLE_LONGLONG(0);
  clear_has_tid();
}
inline ::google::protobuf::int64 Question::tid() const {
  // @@protoc_insertion_point(field_get:chat.Question.tid)
  return tid_;
}
inline void Question::set_tid(::google::protobuf::int64 value) {
  set_has_tid();
  tid_ = value;
  // @@protoc_insertion_point(field_set:chat.Question.tid)
}

// required .chat.ChatRequestType type = 3;
inline bool Question::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Question::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Question::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Question::clear_type() {
  type_ = 8000;
  clear_has_type();
}
inline ::chat::ChatRequestType Question::type() const {
  // @@protoc_insertion_point(field_get:chat.Question.type)
  return static_cast< ::chat::ChatRequestType >(type_);
}
inline void Question::set_type(::chat::ChatRequestType value) {
  assert(::chat::ChatRequestType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:chat.Question.type)
}

// optional string message = 4;
inline bool Question::has_message() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Question::set_has_message() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Question::clear_has_message() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Question::clear_message() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& Question::message() const {
  // @@protoc_insertion_point(field_get:chat.Question.message)
  return *message_;
}
inline void Question::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set:chat.Question.message)
}
inline void Question::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set_char:chat.Question.message)
}
inline void Question::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:chat.Question.message)
}
inline ::std::string* Question::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:chat.Question.message)
  return message_;
}
inline ::std::string* Question::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Question::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:chat.Question.message)
}

// optional bytes pic = 5;
inline bool Question::has_pic() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Question::set_has_pic() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Question::clear_has_pic() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Question::clear_pic() {
  if (pic_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    pic_->clear();
  }
  clear_has_pic();
}
inline const ::std::string& Question::pic() const {
  // @@protoc_insertion_point(field_get:chat.Question.pic)
  return *pic_;
}
inline void Question::set_pic(const ::std::string& value) {
  set_has_pic();
  if (pic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    pic_ = new ::std::string;
  }
  pic_->assign(value);
  // @@protoc_insertion_point(field_set:chat.Question.pic)
}
inline void Question::set_pic(const char* value) {
  set_has_pic();
  if (pic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    pic_ = new ::std::string;
  }
  pic_->assign(value);
  // @@protoc_insertion_point(field_set_char:chat.Question.pic)
}
inline void Question::set_pic(const void* value, size_t size) {
  set_has_pic();
  if (pic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    pic_ = new ::std::string;
  }
  pic_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:chat.Question.pic)
}
inline ::std::string* Question::mutable_pic() {
  set_has_pic();
  if (pic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    pic_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:chat.Question.pic)
  return pic_;
}
inline ::std::string* Question::release_pic() {
  clear_has_pic();
  if (pic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = pic_;
    pic_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Question::set_allocated_pic(::std::string* pic) {
  if (pic_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete pic_;
  }
  if (pic) {
    set_has_pic();
    pic_ = pic;
  } else {
    clear_has_pic();
    pic_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:chat.Question.pic)
}

// optional bytes video = 6;
inline bool Question::has_video() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Question::set_has_video() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Question::clear_has_video() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Question::clear_video() {
  if (video_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    video_->clear();
  }
  clear_has_video();
}
inline const ::std::string& Question::video() const {
  // @@protoc_insertion_point(field_get:chat.Question.video)
  return *video_;
}
inline void Question::set_video(const ::std::string& value) {
  set_has_video();
  if (video_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    video_ = new ::std::string;
  }
  video_->assign(value);
  // @@protoc_insertion_point(field_set:chat.Question.video)
}
inline void Question::set_video(const char* value) {
  set_has_video();
  if (video_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    video_ = new ::std::string;
  }
  video_->assign(value);
  // @@protoc_insertion_point(field_set_char:chat.Question.video)
}
inline void Question::set_video(const void* value, size_t size) {
  set_has_video();
  if (video_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    video_ = new ::std::string;
  }
  video_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:chat.Question.video)
}
inline ::std::string* Question::mutable_video() {
  set_has_video();
  if (video_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    video_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:chat.Question.video)
  return video_;
}
inline ::std::string* Question::release_video() {
  clear_has_video();
  if (video_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = video_;
    video_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Question::set_allocated_video(::std::string* video) {
  if (video_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete video_;
  }
  if (video) {
    set_has_video();
    video_ = video;
  } else {
    clear_has_video();
    video_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:chat.Question.video)
}

// -------------------------------------------------------------------

// Answer

// required string result = 1;
inline bool Answer::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Answer::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Answer::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Answer::clear_result() {
  if (result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    result_->clear();
  }
  clear_has_result();
}
inline const ::std::string& Answer::result() const {
  // @@protoc_insertion_point(field_get:chat.Answer.result)
  return *result_;
}
inline void Answer::set_result(const ::std::string& value) {
  set_has_result();
  if (result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    result_ = new ::std::string;
  }
  result_->assign(value);
  // @@protoc_insertion_point(field_set:chat.Answer.result)
}
inline void Answer::set_result(const char* value) {
  set_has_result();
  if (result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    result_ = new ::std::string;
  }
  result_->assign(value);
  // @@protoc_insertion_point(field_set_char:chat.Answer.result)
}
inline void Answer::set_result(const char* value, size_t size) {
  set_has_result();
  if (result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    result_ = new ::std::string;
  }
  result_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:chat.Answer.result)
}
inline ::std::string* Answer::mutable_result() {
  set_has_result();
  if (result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    result_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:chat.Answer.result)
  return result_;
}
inline ::std::string* Answer::release_result() {
  clear_has_result();
  if (result_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = result_;
    result_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Answer::set_allocated_result(::std::string* result) {
  if (result_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete result_;
  }
  if (result) {
    set_has_result();
    result_ = result;
  } else {
    clear_has_result();
    result_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:chat.Answer.result)
}

// required .chat.ChatRequestType type = 2;
inline bool Answer::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Answer::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Answer::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Answer::clear_type() {
  type_ = 8000;
  clear_has_type();
}
inline ::chat::ChatRequestType Answer::type() const {
  // @@protoc_insertion_point(field_get:chat.Answer.type)
  return static_cast< ::chat::ChatRequestType >(type_);
}
inline void Answer::set_type(::chat::ChatRequestType value) {
  assert(::chat::ChatRequestType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:chat.Answer.type)
}

// optional string message = 3;
inline bool Answer::has_message() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Answer::set_has_message() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Answer::clear_has_message() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Answer::clear_message() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& Answer::message() const {
  // @@protoc_insertion_point(field_get:chat.Answer.message)
  return *message_;
}
inline void Answer::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set:chat.Answer.message)
}
inline void Answer::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set_char:chat.Answer.message)
}
inline void Answer::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:chat.Answer.message)
}
inline ::std::string* Answer::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:chat.Answer.message)
  return message_;
}
inline ::std::string* Answer::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Answer::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:chat.Answer.message)
}

// optional bytes pic = 4;
inline bool Answer::has_pic() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Answer::set_has_pic() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Answer::clear_has_pic() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Answer::clear_pic() {
  if (pic_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    pic_->clear();
  }
  clear_has_pic();
}
inline const ::std::string& Answer::pic() const {
  // @@protoc_insertion_point(field_get:chat.Answer.pic)
  return *pic_;
}
inline void Answer::set_pic(const ::std::string& value) {
  set_has_pic();
  if (pic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    pic_ = new ::std::string;
  }
  pic_->assign(value);
  // @@protoc_insertion_point(field_set:chat.Answer.pic)
}
inline void Answer::set_pic(const char* value) {
  set_has_pic();
  if (pic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    pic_ = new ::std::string;
  }
  pic_->assign(value);
  // @@protoc_insertion_point(field_set_char:chat.Answer.pic)
}
inline void Answer::set_pic(const void* value, size_t size) {
  set_has_pic();
  if (pic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    pic_ = new ::std::string;
  }
  pic_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:chat.Answer.pic)
}
inline ::std::string* Answer::mutable_pic() {
  set_has_pic();
  if (pic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    pic_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:chat.Answer.pic)
  return pic_;
}
inline ::std::string* Answer::release_pic() {
  clear_has_pic();
  if (pic_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = pic_;
    pic_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Answer::set_allocated_pic(::std::string* pic) {
  if (pic_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete pic_;
  }
  if (pic) {
    set_has_pic();
    pic_ = pic;
  } else {
    clear_has_pic();
    pic_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:chat.Answer.pic)
}

// optional bytes video = 5;
inline bool Answer::has_video() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Answer::set_has_video() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Answer::clear_has_video() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Answer::clear_video() {
  if (video_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    video_->clear();
  }
  clear_has_video();
}
inline const ::std::string& Answer::video() const {
  // @@protoc_insertion_point(field_get:chat.Answer.video)
  return *video_;
}
inline void Answer::set_video(const ::std::string& value) {
  set_has_video();
  if (video_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    video_ = new ::std::string;
  }
  video_->assign(value);
  // @@protoc_insertion_point(field_set:chat.Answer.video)
}
inline void Answer::set_video(const char* value) {
  set_has_video();
  if (video_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    video_ = new ::std::string;
  }
  video_->assign(value);
  // @@protoc_insertion_point(field_set_char:chat.Answer.video)
}
inline void Answer::set_video(const void* value, size_t size) {
  set_has_video();
  if (video_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    video_ = new ::std::string;
  }
  video_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:chat.Answer.video)
}
inline ::std::string* Answer::mutable_video() {
  set_has_video();
  if (video_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    video_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:chat.Answer.video)
  return video_;
}
inline ::std::string* Answer::release_video() {
  clear_has_video();
  if (video_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = video_;
    video_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void Answer::set_allocated_video(::std::string* video) {
  if (video_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete video_;
  }
  if (video) {
    set_has_video();
    video_ = video;
  } else {
    clear_has_video();
    video_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:chat.Answer.video)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace chat

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::chat::ChatRequestType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::chat::ChatRequestType>() {
  return ::chat::ChatRequestType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_chat_2eproto__INCLUDED
